<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<RootNamespace>Downed</RootNamespace>
		<LangVersion>default</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>Downed</AssemblyName>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="BoneLib">
		  <HintPath>$(HOME)/repos/BL-Libs/Mods/BoneLib.dll</HintPath>
		</Reference>
		<Reference Include="MelonLoader">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/net6/MelonLoader.dll</HintPath>
		</Reference>
		<Reference Include="RagdollPlayer">
		  <HintPath>$(HOME)/repos/BL-Libs/Mods/RagdollPlayer.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSLZ.Marrow">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/Il2CppSLZ.Marrow.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/net6/Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
		  <HintPath>$(HOME)/repos/BL-Libs/PC/MelonLoader/Il2CppAssemblies/Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="LabFusion">
		  <HintPath>$(HOME)/repos/BL-Libs/Mods/LabFusion.dll</HintPath>
		  <Private>false</Private>
		</Reference>
	</ItemGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Downed.cs" />
		<Compile Include="FusionCompat.cs"/>
	</ItemGroup>

	<Target Name="CopyOutput" AfterTargets="Build" Condition="'$(HOME)/repos/Downed/Mods/Mods' != ''">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(HOME)/repos/Downed/Mods/Mods" />
	</Target>	
</Project>
